{% set name = "ptarcade" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptarcade-{{ version }}.tar.gz
  sha256: 1083a040686cb3985bb066a41dca6dbc41a2b55421f735868c80b39a6fc83d2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv
    - pip
  run:
    - python >={{ python_min }},<3.13
    - ptmcmcsampler >=2.1.1,<3.0.0
    - mpi4py >=3.1.4,<5.0.0
    - h5py >=3.8.0,<4.0.0
    - enterprise-pulsar >=3.4.3,<4.0.0
    - enterprise_extensions >=3.0.0,<4.0.0
    - natpy >=0.1.1,<1.0.0
    - numpy >=1.24.3,<3.0.0
    - pandas >=2.0.2,<3.0.0
    - pyarrow >=12.0.0
    - getdist >=1.4.6,<2.0.0
    - astroml >=1.0.2.post1,<2.0.0
    - scipy >=1.10.1,<2.0.0
    - encor >=1.1.5,<2.0.0
    - rich >=13.4.2,<15.0.0
    - ceffyl >=1.41.1,<1.50
    - setuptools >=80.0.0
    - astropy >=5.3.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - ptarcade
  commands:
    - pip check

about:
  home: https://andrea-mitridate.github.io/PTArcade/
  summary: PTArcade provides an interface to the ENTERPRISE analysis suite and allows for simple implementation of new-physics searches in PTA data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
    - andrea-mitridate
