{% set name = "ptarcade" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptarcade-{{ version }}.tar.gz
  sha256: 52c039c173e5f1b3bcfb42908e6b73a43b91aa007bf4b383802e0b27207fe40e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<3.11
    - ptmcmcsampler >=2.1.1,<3.0.0
    - mpi4py >=3.1.4,<4.0.0
    - h5py >=3.8.0,<4.0.0
    - enterprise-pulsar >=3.3.2,<4.0.0
    - enterprise_extensions >=2.4.2,<3.0.0
    - scikit-sparse >=0.4.12,<1.0.0
    - natpy >=0.1.1,<1.0.0
    - numpy >=1.20.0,<2.0.0
    - pandas >=2.0.2,<3.0.0
    - getdist >=1.4.1,<2.0.0
    - astroml >=1.0.2,<2.0.0
    - scipy >=1.10.1,<2.0.0
    - encor >=1.1.2,<2.0.0
    - ceffyl >=1.26.0,<2.0.0
    - pytables >=3.8.0,<4.0.0
    - rich >=13.4.2,<14.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ptarcade

about:
  home: https://andrea-mitridate.github.io/PTArcade/
  summary: PTArcade provides an interface to the ENTERPRISE analysis suite and allows for simple implementation of new-physics searches in PTA data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
    - andrea-mitridate
